import Navegador from './components/navegador'
import './globals.css'
import { Inter } from 'next/font/google'
import Pie from './components/pie';
import Anuncios from './components/anuncios';



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Koko Conservas',
  description: 'Generated by create next app',
  
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      
      
      <body className={inter.className}>
      <Anuncios/>
      <Navegador/>
        
      
        {children}
        
      <Pie/>
      </body>
      
    </html>
  )
}
